name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python  # If you need Python for building your docs
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build the Docs  # Replace this with your actual build steps
        run: |
          # Add commands here to build your documentation
          # For example, if you're using Sphinx:
          pip install sphinx
          sphinx-build -M html docs/source/ docs/build/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Adjust this path to where your built HTML files are
